### ISSUE TITLE
Screenshot?  Window is clipping....

### ISSUE THREAD

**Issue by PySimpleGUI** [geohwk/DatasetManipulationTool#1]
Hiya!

I can't help but notice your project has a GUI.

![image](https://user-images.githubusercontent.com/46163555/155905123-44768329-fe20-4639-88fb-b24bdcb6683b.png)

Drop a screenshot in your readme and you'll have happy visitors.

On my machine, your window is getting cut off.  It's because of the hard-coded size on your window.  Removing the size parameter and I'm able to see the entire window.  

![image](https://user-images.githubusercontent.com/46163555/155905195-4f00eae9-84ee-403c-a135-bc5fdeb82879.png)

I like the color choices 

![image](https://user-images.githubusercontent.com/46163555/155905215-55f8ced6-9ff3-4c2e-8bcf-0d2479001a70.png)

**Comment by geohwk** [comment]
Thanks for the feedback, appreciate that. I have now removed the explicit sizing and included a little screenshot in the Readme (After much trial and error). Thanks Again!

**Comment by PySimpleGUI** [comment]
You bet!  I was in the neighborhood and thought I would stop in and mention what I saw in your GUI.  Glad you've learned how to do screenshots so you can share future programs you write.

I use a commercial program, Snagit, for my screenshots and the free ShareX program for my GIFs.  There's an active project, `psgscreenshot`, that will enable PySimpleGUI users to easily capture screenshots and optionally upload them to a public gallery/catalog.

While you're editing your Readme, you may want to mention the packages you're using.... like OpenCV and PySimpleGUI.  This will get your project visibility just as the screenshot does.  You'll be found in searches for example.  It seems like your tool will be usable in a general way since it manipulates datasets.  It's not a bad practice/habit to use for Open Source projects.

Congrats on the progress with your progress this weekend.
